package com.jimboyz.printingsystem.controlPanel;

public class JasperReportGenerator {
	public static String setBillingReport(String font, String isBold, String isItalic, String isUnderline, String isStrikeThrough, String addressFontSize, String fontSize, String fontColor) {
		String report = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
				+ "<!-- Created with Jaspersoft Studio version 6.20.5.final using JasperReports Library version 6.20.5-3efcf2e67f959db3888d79f73dde2dbd7acb4f8e  -->\r\n"
				+ "<jasperReport xmlns=\"http://jasperreports.sourceforge.net/jasperreports\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd\" name=\"forPrintingSystemJimboyz_Jan052024\" pageWidth=\"297\" pageHeight=\"425\" columnWidth=\"257\" leftMargin=\"20\" rightMargin=\"20\" topMargin=\"20\" bottomMargin=\"20\" uuid=\"e0e9e97d-deba-4d13-988d-5d141ae9f454\">\r\n"
				+ "	<property name=\"com.jaspersoft.studio.data.sql.tables\">\r\n"
				+ "		<![CDATA[YmlsbGluZ1N0YXRlbWVudCAsMTUsMTUsNDFmNzRjMjAtZjE1YS00MTQ5LWI3OWQtZjIwY2MzOWQ5\r\n"
				+ "ZTY4Ow==]]>\r\n"
				+ "	</property>\r\n"
				+ "	<property name=\"com.jaspersoft.studio.data.defaultdataadapter\" value=\"forPrintingSystemJan052024\"/>\r\n"
				+ "	<property name=\"com.jaspersoft.studio.unit.\" value=\"pixel\"/>\r\n"
				+ "	<property name=\"com.jaspersoft.studio.unit.pageHeight\" value=\"cm\"/>\r\n"
				+ "	<property name=\"com.jaspersoft.studio.unit.pageWidth\" value=\"cm\"/>\r\n"
				+ "	<property name=\"com.jaspersoft.studio.unit.topMargin\" value=\"pixel\"/>\r\n"
				+ "	<property name=\"com.jaspersoft.studio.unit.bottomMargin\" value=\"pixel\"/>\r\n"
				+ "	<property name=\"com.jaspersoft.studio.unit.leftMargin\" value=\"pixel\"/>\r\n"
				+ "	<property name=\"com.jaspersoft.studio.unit.rightMargin\" value=\"pixel\"/>\r\n"
				+ "	<property name=\"com.jaspersoft.studio.unit.columnWidth\" value=\"pixel\"/>\r\n"
				+ "	<property name=\"com.jaspersoft.studio.unit.columnSpacing\" value=\"pixel\"/>\r\n"
				+ "	<parameter name=\"name\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"address\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"term\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"tin\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"osca\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"businessStyle\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"cardholder\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"qty1\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"qty2\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"qty3\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"qty4\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"qty5\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"qty6\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"qty7\" class=\"java.lang.String\" isForPrompting=\"false\"/>\r\n"
				+ "	<parameter name=\"unit1\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"unit2\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"unit3\" class=\"java.lang.String\" isForPrompting=\"false\"/>\r\n"
				+ "	<parameter name=\"unit4\" class=\"java.lang.String\" isForPrompting=\"false\"/>\r\n"
				+ "	<parameter name=\"unit5\" class=\"java.lang.String\" isForPrompting=\"false\"/>\r\n"
				+ "	<parameter name=\"unit6\" class=\"java.lang.String\" isForPrompting=\"false\"/>\r\n"
				+ "	<parameter name=\"unit7\" class=\"java.lang.String\" isForPrompting=\"false\"/>\r\n"
				+ "	<parameter name=\"des1\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"des2\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"des3\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"des4\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"des5\" class=\"java.lang.String\" isForPrompting=\"false\"/>\r\n"
				+ "	<parameter name=\"des6\" class=\"java.lang.String\" isForPrompting=\"false\"/>\r\n"
				+ "	<parameter name=\"des7\" class=\"java.lang.String\" isForPrompting=\"false\"/>\r\n"
				+ "	<parameter name=\"unitPrice1\" class=\"java.lang.String\" isForPrompting=\"false\"/>\r\n"
				+ "	<parameter name=\"unitPrice2\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"unitPrice3\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"unitPrice4\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"unitPrice5\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"unitPrice6\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"unitPrice7\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"amount1\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"amount2\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"amount3\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"amount4\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"amount5\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"amount6\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"amount7\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"totalSales\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"lessVat\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"lessdis\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"amountNet\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"amountDue\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"totalAmountDue\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"vatables\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"vatExempt\" class=\"java.lang.String\" isForPrompting=\"false\"/>\r\n"
				+ "	<parameter name=\"zrs\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"vatAmount\" class=\"java.lang.String\" isForPrompting=\"false\"/>\r\n"
				+ "	<parameter name=\"customerName\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"by\" class=\"java.lang.String\"/>\r\n"
				+ "	<parameter name=\"date\" class=\"java.lang.String\"/>\r\n"
				+ "	<queryString language=\"SQL\">\r\n"
				+ "		<![CDATA[SELECT *\r\n"
				+ "FROM billingStatement\r\n"
				+ "WHERE \r\n"
				+ "	 billingStatement.id = $P{name}]]>\r\n"
				+ "	</queryString>\r\n"
				+ "	<field name=\"name\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"name\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"name\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"id\" class=\"java.lang.Integer\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"id\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"id\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"address\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"address\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"address\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"tin\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"tin\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"tin\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"term\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"term\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"term\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"osca\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"osca\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"osca\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"cardholder\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"cardholder\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"cardholder\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"businessStyle\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"businessStyle\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"businessStyle\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"qty1\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"qty1\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"qty1\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unit1\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unit1\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unit1\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"des1\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"des1\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"des1\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"qty2\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"qty2\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"qty2\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unit2\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unit2\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unit2\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"des2\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"des2\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"des2\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"qty3\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"qty3\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"qty3\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unit3\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unit3\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unit3\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"des3\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"des3\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"des3\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"qty4\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"qty4\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"qty4\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unit4\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unit4\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unit4\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"des4\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"des4\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"des4\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"qty5\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"qty5\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"qty5\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unit5\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unit5\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unit5\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"des5\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"des5\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"des5\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"qty6\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"qty6\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"qty6\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unit6\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unit6\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unit6\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"des6\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"des6\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"des6\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"qty7\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"qty7\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"qty7\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unit7\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unit7\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unit7\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"des7\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"des7\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"des7\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unitPrice1\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unitPrice1\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unitPrice1\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unitPrice2\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unitPrice2\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unitPrice2\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unitPrice3\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unitPrice3\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unitPrice3\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unitPrice4\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unitPrice4\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unitPrice4\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unitPrice5\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unitPrice5\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unitPrice5\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unitPrice6\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unitPrice6\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unitPrice6\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"unitPrice7\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"unitPrice7\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"unitPrice7\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"amount1\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"amount1\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"amount1\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"amount2\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"amount2\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"amount2\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"amount3\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"amount3\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"amount3\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"amount4\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"amount4\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"amount4\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"amount5\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"amount5\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"amount5\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"amount6\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"amount6\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"amount6\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"amount7\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"amount7\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"amount7\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"totalSales\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"totalSales\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"totalSales\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"lessVat\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"lessVat\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"lessVat\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"vatables\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"vatables\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"vatables\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"amountNet\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"amountNet\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"amountNet\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"vatExempt\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"vatExempt\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"vatExempt\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"lessdis\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"lessdis\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"lessdis\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"zrs\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"zrs\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"zrs\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"amountDue\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"amountDue\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"amountDue\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"vatAmount\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"vatAmount\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"vatAmount\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"totalAmountDue\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"totalAmountDue\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"totalAmountDue\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"customerName\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"customerName\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"customerName\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"by\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"by\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"by\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<field name=\"date\" class=\"java.lang.String\">\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.name\" value=\"date\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.label\" value=\"date\"/>\r\n"
				+ "		<property name=\"com.jaspersoft.studio.field.tree.path\" value=\"bilingstatement\"/>\r\n"
				+ "	</field>\r\n"
				+ "	<group name=\"name\">\r\n"
				+ "		<groupExpression><![CDATA[$P{name}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"address\">\r\n"
				+ "		<groupExpression><![CDATA[$P{address}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"tin\">\r\n"
				+ "		<groupExpression><![CDATA[$P{tin}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"term\">\r\n"
				+ "		<groupExpression><![CDATA[$P{term}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"osca\">\r\n"
				+ "		<groupExpression><![CDATA[$P{osca}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"cardholder\">\r\n"
				+ "		<groupExpression><![CDATA[$P{cardholder}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"businessStyle\">\r\n"
				+ "		<groupExpression><![CDATA[$P{businessStyle}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"qty1\">\r\n"
				+ "		<groupExpression><![CDATA[$P{qty1}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"unit1\">\r\n"
				+ "		<groupExpression><![CDATA[$P{unit1}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"des1\">\r\n"
				+ "		<groupExpression><![CDATA[$P{des1}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"qty2\">\r\n"
				+ "		<groupExpression><![CDATA[$P{qty2}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"unit2\">\r\n"
				+ "		<groupExpression><![CDATA[$P{unit2}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"des2\">\r\n"
				+ "		<groupExpression><![CDATA[$P{des2}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"qty3\">\r\n"
				+ "		<groupExpression><![CDATA[$P{qty3}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"unit3\">\r\n"
				+ "		<groupExpression><![CDATA[$P{unit3}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"des3\">\r\n"
				+ "		<groupExpression><![CDATA[$P{des3}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"qty4\">\r\n"
				+ "		<groupExpression><![CDATA[$P{qty4}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"unit4\">\r\n"
				+ "		<groupExpression><![CDATA[$P{unit4}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"des4\">\r\n"
				+ "		<groupExpression><![CDATA[$P{des4}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"qty5\">\r\n"
				+ "		<groupExpression><![CDATA[$P{qty5}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"unit5\">\r\n"
				+ "		<groupExpression><![CDATA[$P{unit5}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"des5\">\r\n"
				+ "		<groupExpression><![CDATA[$P{des5}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"qty6\">\r\n"
				+ "		<groupExpression><![CDATA[$P{qty6}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"unit6\">\r\n"
				+ "		<groupExpression><![CDATA[$P{unit6}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"des6\">\r\n"
				+ "		<groupExpression><![CDATA[$P{des6}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"qty7\">\r\n"
				+ "		<groupExpression><![CDATA[$P{qty7}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"unit7\">\r\n"
				+ "		<groupExpression><![CDATA[$P{unit7}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"des7\">\r\n"
				+ "		<groupExpression><![CDATA[$P{des7}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"totalSales\">\r\n"
				+ "		<groupExpression><![CDATA[$P{totalSales}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"lessVat\">\r\n"
				+ "		<groupExpression><![CDATA[$P{lessVat}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"vatables\">\r\n"
				+ "		<groupExpression><![CDATA[$P{vatables}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"amountNet\">\r\n"
				+ "		<groupExpression><![CDATA[$P{amountNet}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"vatExempt\">\r\n"
				+ "		<groupExpression><![CDATA[$P{vatExempt}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"lessdis\">\r\n"
				+ "		<groupExpression><![CDATA[$P{lessdis}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"zrs\">\r\n"
				+ "		<groupExpression><![CDATA[$P{zrs}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"amountDue\">\r\n"
				+ "		<groupExpression><![CDATA[$P{amountDue}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"vatAmount\">\r\n"
				+ "		<groupExpression><![CDATA[$P{vatAmount}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"totalAmountDue\">\r\n"
				+ "		<groupExpression><![CDATA[$P{totalAmountDue}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"customerName\">\r\n"
				+ "		<groupExpression><![CDATA[$P{customerName}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<group name=\"by\">\r\n"
				+ "		<groupExpression><![CDATA[$P{by}]]></groupExpression>\r\n"
				+ "	</group>\r\n"
				+ "	<background>\r\n"
				+ "		<band splitType=\"Stretch\"/>\r\n"
				+ "	</background>\r\n"
				+ "	<title>\r\n"
				+ "		<band splitType=\"Stretch\"/>\r\n"
				+ "	</title>\r\n"
				+ "	<pageHeader>\r\n"
				+ "		<band height=\"71\" splitType=\"Stretch\">\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"200\" y=\"5\" width=\"71\" height=\"15\" uuid=\"dff4f127-b43e-4ce4-993e-04c2daddbe07\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{date}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"40\" width=\"271\" height=\"13\" uuid=\"ab138eec-0ea0-4c22-80fc-b255c69c7894\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{name}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"55\" width=\"271\" height=\"13\" uuid=\"92c3b0ab-d30a-4e2d-b448-ebd6552ef39e\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+addressFontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{address}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "		</band>\r\n"
				+ "	</pageHeader>\r\n"
				+ "	<columnHeader>\r\n"
				+ "		<band height=\"290\" splitType=\"Stretch\">\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"0\" width=\"160\" height=\"13\" uuid=\"73e00fe9-3504-4dbd-8bb6-dccf45650097\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{tin}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"30\" y=\"17\" width=\"125\" height=\"13\" uuid=\"0a482220-e08c-45cc-86cb-910fe00cf7d0\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{osca}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"190\" y=\"0\" width=\"79\" height=\"13\" uuid=\"98bd95df-ab20-4ec2-965f-e75f00d0e318\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{term}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"22\" y=\"32\" width=\"158\" height=\"13\" uuid=\"3982dc69-24ae-4698-b603-8c6472cd84d4\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{businessStyle}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"191\" y=\"31\" width=\"79\" height=\"13\" uuid=\"a5df5579-dc66-4d6b-8016-c3369367113c\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{cardholder}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"58\" width=\"35\" height=\"13\" uuid=\"fd6f2825-0f06-4936-aad5-5e5f35b96ff7\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{qty1}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"36\" y=\"58\" width=\"35\" height=\"13\" uuid=\"5b702a49-5000-4893-b766-cbe270599448\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unit1}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"72\" y=\"58\" width=\"115\" height=\"13\" uuid=\"9c452042-bdbd-49b3-9b96-7ad18ca80c89\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{des1}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"233\" y=\"58\" width=\"44\" height=\"13\" uuid=\"034f5d9f-2a60-420b-b7fb-ef3b5c6ff360\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{amount1}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"188\" y=\"58\" width=\"44\" height=\"13\" uuid=\"d1cc4c49-d7ca-46d6-8df7-39e1c7beeb04\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unitPrice1}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"72\" width=\"35\" height=\"13\" uuid=\"c62b8fe3-3de7-42b8-a990-2d24f5de97b3\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{qty2}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"36\" y=\"72\" width=\"35\" height=\"13\" uuid=\"3bcfb599-4cf7-42f3-a2bf-3d12ae841201\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unit2}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"72\" y=\"72\" width=\"115\" height=\"13\" uuid=\"a7e8a179-252e-40c8-88c6-df13513b0c05\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{des2}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"188\" y=\"72\" width=\"44\" height=\"13\" uuid=\"88f038e9-8875-494c-a926-1ea20d4193d9\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unitPrice2}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"233\" y=\"72\" width=\"44\" height=\"13\" uuid=\"42274463-f3a2-480b-b603-4eb35f28929e\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{amount2}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"86\" width=\"35\" height=\"13\" uuid=\"1cded456-64cb-494c-b83b-02c428e87bd1\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{qty3}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"36\" y=\"86\" width=\"35\" height=\"13\" uuid=\"6a7c415b-5479-457b-9c22-11f3eb241afb\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unit3}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"72\" y=\"86\" width=\"115\" height=\"13\" uuid=\"d8308db6-0051-4eef-8261-b2629447668c\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{des3}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"188\" y=\"86\" width=\"44\" height=\"13\" uuid=\"5ad2fdde-e08b-4473-bcf4-163aedfca8ba\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unitPrice3}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"233\" y=\"86\" width=\"44\" height=\"13\" uuid=\"e84e923c-207d-4de6-8738-7a4efa6b3d67\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{amount3}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"100\" width=\"35\" height=\"13\" uuid=\"7396b732-14d2-4f97-b172-7fcb7387cffb\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{qty4}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"72\" y=\"100\" width=\"115\" height=\"13\" uuid=\"b8dba451-c6f2-4438-9782-724f33f87aec\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{des4}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"233\" y=\"114\" width=\"44\" height=\"13\" uuid=\"f757512d-7927-4468-baae-b1b43234abe2\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{amount5}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"188\" y=\"100\" width=\"44\" height=\"13\" uuid=\"9f84c850-f277-49db-bbe1-38dcba546b31\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unitPrice4}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"128\" width=\"35\" height=\"13\" uuid=\"9581d158-9d71-4546-8857-ba5b7884b348\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{qty6}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"188\" y=\"128\" width=\"44\" height=\"13\" uuid=\"a52d7597-68b0-42b5-975d-9925f49693bc\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unitPrice6}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"233\" y=\"100\" width=\"44\" height=\"13\" uuid=\"9d117de9-3034-4716-93b8-a9ffb8786a5e\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{amount4}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"72\" y=\"128\" width=\"115\" height=\"13\" uuid=\"e4dd3cf4-56c0-429f-bf34-3e3d91a7b008\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{des6}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"36\" y=\"128\" width=\"35\" height=\"13\" uuid=\"63f1c0d7-ec65-4875-83e2-7d680f0c2bd7\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unit6}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"36\" y=\"114\" width=\"35\" height=\"13\" uuid=\"8a7922d1-8f4a-4e01-a90c-ff4da8bc638c\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unit5}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"233\" y=\"128\" width=\"44\" height=\"13\" uuid=\"d5e36b31-5360-4137-addf-27587b470c03\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{amount6}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"114\" width=\"35\" height=\"13\" uuid=\"81ce29bf-a96b-44e5-bdec-c763595cd2dc\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{qty5}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"72\" y=\"114\" width=\"115\" height=\"13\" uuid=\"2484692c-3d31-4992-b1c3-fd2b29aef00b\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{des5}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"36\" y=\"100\" width=\"35\" height=\"13\" uuid=\"1d759844-ad42-4c2e-b34d-0b636bd6441c\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unit4}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"188\" y=\"114\" width=\"44\" height=\"13\" uuid=\"925294f2-d4ae-4192-8db0-4202f0c64898\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unitPrice5}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"233\" y=\"142\" width=\"44\" height=\"13\" uuid=\"9ad87b38-3cad-4344-a29b-38c7f030f330\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{amount7}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"36\" y=\"142\" width=\"35\" height=\"13\" uuid=\"d988b3c8-e8ec-49f4-b2a2-cb99ab84fd19\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unit7}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"188\" y=\"142\" width=\"44\" height=\"13\" uuid=\"32867aab-b1de-48f4-b351-75253b704fb1\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{unitPrice7}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"72\" y=\"142\" width=\"115\" height=\"13\" uuid=\"d132a24c-3d9f-4186-a943-fbfd138cbeca\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{des7}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"142\" width=\"35\" height=\"13\" uuid=\"31856769-098a-4a53-b716-3d4330978551\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{qty7}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"232\" y=\"212\" width=\"44\" height=\"13\" uuid=\"981aca7e-172d-44f2-898d-add942874314\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{amountDue}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"233\" y=\"156\" width=\"44\" height=\"13\" uuid=\"0421d559-5cd7-4fbe-b02f-26dfcde2bd64\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{totalSales}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"198\" width=\"40\" height=\"13\" uuid=\"285f8945-dd4b-4aef-a942-56bf438f5a54\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"171\" y=\"212\" width=\"40\" height=\"13\" uuid=\"32bbc4a5-3841-44a5-a49d-234f087b2310\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"170\" width=\"40\" height=\"13\" uuid=\"d34a9782-44b1-4f64-998c-6531b2a28dde\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"171\" y=\"198\" width=\"40\" height=\"13\" uuid=\"7a39267b-9aa8-458c-a3cb-4618727ab06c\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"40\" y=\"184\" width=\"40\" height=\"13\" uuid=\"cbbafe8d-aa8b-4fed-8128-a0f09c511c53\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"232\" y=\"198\" width=\"44\" height=\"13\" uuid=\"3468b5bc-e624-4a20-a2dd-65c7658b0558\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{lessdis}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"72\" y=\"170\" width=\"151\" height=\"13\" uuid=\"3ef68931-49b2-4117-9c8e-ea39807b844e\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"41\" y=\"170\" width=\"30\" height=\"13\" uuid=\"e0179615-c2c0-439f-aedb-8aa15ffb7c2e\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"81\" y=\"184\" width=\"89\" height=\"13\" uuid=\"7008e910-ce12-45e0-83b0-94a1e1b80cb7\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{vatables}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"233\" y=\"170\" width=\"44\" height=\"13\" uuid=\"1c09906e-14b8-40cb-bc74-16519e9b46f6\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{lessVat}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"72\" y=\"156\" width=\"151\" height=\"13\" uuid=\"3f38355a-59b1-43e4-86c2-74de7a743bb1\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"81\" y=\"198\" width=\"89\" height=\"13\" uuid=\"7d8aefeb-85b8-4aac-ba19-01d698959127\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{vatExempt}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"40\" y=\"198\" width=\"40\" height=\"13\" uuid=\"0a7c6515-9784-4c0d-9891-d3a948b8cfee\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"40\" y=\"212\" width=\"40\" height=\"13\" uuid=\"ed3797cb-201a-468b-8468-97fa4adccf8a\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"171\" y=\"184\" width=\"40\" height=\"13\" uuid=\"9d206fa9-b88e-41a7-801b-1e9f3dcd829e\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"81\" y=\"212\" width=\"89\" height=\"13\" uuid=\"1d464a11-3c8f-492f-b5d9-eaeefec4b176\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{zrs}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"41\" y=\"156\" width=\"30\" height=\"13\" uuid=\"65fb663e-06a5-4cc8-9c74-1f88398dd728\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"184\" width=\"40\" height=\"13\" uuid=\"42f8f411-f375-435e-9468-27684a3fe7d5\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"232\" y=\"184\" width=\"44\" height=\"13\" uuid=\"87f38d12-c0a0-4a65-a62c-851ca98ede0e\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{amountNet}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"156\" width=\"40\" height=\"13\" uuid=\"4b2b8577-c30e-4d3e-862b-0965a1863a4e\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"212\" width=\"40\" height=\"13\" uuid=\"4700a66b-ffbf-499a-9dd8-9ba5d24269ad\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"0\" y=\"226\" width=\"40\" height=\"13\" uuid=\"58cb034d-4430-4f64-825b-9bab4b355e8a\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"40\" y=\"226\" width=\"40\" height=\"13\" uuid=\"ce85fb1e-adcf-49d7-86ba-0be1529e0a0b\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"81\" y=\"226\" width=\"89\" height=\"13\" uuid=\"f2925f55-0c7c-43d9-acd6-88f1cde74b03\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{vatAmount}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"171\" y=\"226\" width=\"40\" height=\"13\" uuid=\"a9d707d2-0166-4b28-bc57-a8b717979f3a\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[\"\"]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"232\" y=\"226\" width=\"44\" height=\"13\" uuid=\"3f90c6ad-a0b8-4283-9e11-3482af3b7df0\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{totalAmountDue}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"168\" y=\"254\" width=\"109\" height=\"13\" uuid=\"d5f4fffa-bfad-4353-8bd4-c6f8c3ccc5f3\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{customerName}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "			<textField>\r\n"
				+ "				<reportElement forecolor=\""+fontColor+"\" x=\"168\" y=\"276\" width=\"109\" height=\"13\" uuid=\"ba06b237-d8db-447c-ae95-518e67db07f5\"/>\r\n"
				+ "				<textElement>\r\n"
				+ "					<font isBold=\""+isBold+"\" isItalic=\""+isItalic+"\" isUnderline=\""+isUnderline+"\" isStrikeThrough=\""+isStrikeThrough+"\" fontName=\""+font+"\" size=\""+fontSize+"\"/>\r\n"
				+ "				</textElement>\r\n"
				+ "				<textFieldExpression><![CDATA[$P{by}]]></textFieldExpression>\r\n"
				+ "			</textField>\r\n"
				+ "		</band>\r\n"
				+ "	</columnHeader>\r\n"
				+ "</jasperReport>\r\n"
				+ "";
		
		
		
		return report;
	}
}
